// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcjpHmim0sb6gPQf3fdPXfAnwSjAzZAM',
    appId: '1:846275958727:web:6b5d39b7c078d8e7516be2',
    messagingSenderId: '846275958727',
    projectId: 'cinext-amiii',
    authDomain: 'cinext-amiii.firebaseapp.com',
    databaseURL: 'https://cinext-amiii-default-rtdb.firebaseio.com',
    storageBucket: 'cinext-amiii.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBFXlAJIdX-aC6y78gEMM5fAzp5y370M',
    appId: '1:846275958727:android:3686693cd736379a516be2',
    messagingSenderId: '846275958727',
    projectId: 'cinext-amiii',
    databaseURL: 'https://cinext-amiii-default-rtdb.firebaseio.com',
    storageBucket: 'cinext-amiii.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcjpHmim0sb6gPQf3fdPXfAnwSjAzZAM',
    appId: '1:846275958727:web:aada5e3a6c9f65f0516be2',
    messagingSenderId: '846275958727',
    projectId: 'cinext-amiii',
    authDomain: 'cinext-amiii.firebaseapp.com',
    databaseURL: 'https://cinext-amiii-default-rtdb.firebaseio.com',
    storageBucket: 'cinext-amiii.firebasestorage.app',
  );
}
